#!/bin/bash
#SBATCH --job-name=sim_SEIR
#SBATCH --output=slurm-out.txt
#SBATCH --error=slurm-err.txt
#SBATCH --time=03:00:00
#SBATCH --cpus-per-task=1
#SBATCH --mem=24GB
#SBATCH -A mrc-bsu-sl2-cpu
#SBATCH --partition=cclake-himem
#SBATCH --array=0-99

## Initialize work environment like
. /etc/profile.d/modules.sh                # Leave this line (enables the module command)
module purge                               # Removes all modules still loaded
module load rhel7/default-ccl              # REQUIRED - loads the basic environment

cd ..
source .venv/bin/activate
python sim_study_binomial/02_run_mcmc.py
