#!/bin/bash
#SBATCH --job-name=CIS_SEIR
#SBATCH --output=slurm/out_%a.txt
#SBATCH --error=slurm/err_%a.txt
#SBATCH --time=04:00:00
#SBATCH --cpus-per-task=1
#SBATCH --mem=24GB
#SBATCH -A mrc-bsu-sl2-cpu
#SBATCH --partition=icelake-himem
#SBATCH --array=0-35

## Initialize work environment like
. /etc/profile.d/modules.sh                # Leave this line (enables the module command)
module purge                               # Removes all modules still loaded
module load rhel7/default-ccl              # REQUIRED - loads the basic environment

cd ..
source .venv/bin/activate
python CIS/run_MCMC.py $SLURM_ARRAY_TASK_ID
